inherits:
    - strictness_high


ignore:
  - venv
  - tests
  - .pytest_cache/


output-format: grouped

test-warnings: true
doc-warnings: true

autodetect: false

uses:
  - numpy
  - re
  - os
  - random
  - dotenv
  - datetime
  - http
  - collections
  - freecurrencyapi
  - sqlite3
  - csv
  - logging

pep8:
    # style checking
    run: true
    options:
        max-line-length: 120

pylint:
    # static analysis and then some
    run: true
    options:
        max-line-length: 120
        # pytest module has dynamically assigned functions,
        # raising errors such as: E1101: Module 'pytest' has
        # no 'mark' member
        ignored-classes: pytest
    disable:
        # Too many lines in module
        - C0302
        # Used * or ** magic
        - W0142
        # Used builtin function 'filter'.
        # (For maintainability, one should prefer list comprehension.)
        - W0141

pydocstyle:
    disable:
      - D212

# prospector --profile .prospector.yaml